### ISSUE TITLE
[Question, not an issue] Is there a way to dismiss/close the tool tip manually?

### ISSUE THREAD

**Issue by glennposadas** [metinkilicaslan/MKToolTip#3]
Very cool library. :) So yeah, my question is in the title. Thanks!

PS. The reason for this is that I experienced ONCE when the second screen was pushed and it has the tooltip but that tooltip is shown and is by/for  the first screen.

**Comment by metinkilicaslan** [comment]
Hi @glennposadas, thank you :)

Unfortunately, It doesn't support it. You can't dismiss it manually but it would be nice to have as a feature. I will try to add it to the next version. I'll let you know :)

**Comment by pareshios** [comment]
Is there any way to get tap on bubble?

**Comment by pareshios** [comment]
extension MKToolTip {
    open override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        Logger.log(point)
        if let viewOfTouch = super.hitTest(point, with: event) {
            return viewOfTouch
        }
        return nil
    }
}
Used this function in MKToolTip extension worked for me
